#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage examples:"
  echo "  $ $(basename -- "$0") dev"
  echo "  $ $(basename -- "$0") prod"
  exit 1
fi

set -euo pipefail # exit on error; treat unset variables as errors; exit on errors in piped commands
SELF_DIR="$(perl -e 'use File::Basename; use Cwd "abs_path"; print dirname(abs_path(@ARGV[0]));' -- "$0")" # figure out the absolute path to the current script, regardless of pwd (perl is more cross-platform than realpath; https://stackoverflow.com/a/30795461)

$SELF_DIR/../backend/build.sh

aws s3 cp \
  --profile vigilant-sniffle \
  backend/dist/backend-lambda.zip \
  s3://vigilant-sniffle-$1-backend/

aws lambda update-function-code \
  --profile vigilant-sniffle \
  --function-name vigilant-sniffle-$1-api-$1-vigilant-sniffle-com \
  --s3-bucket vigilant-sniffle-$1-backend \
  --s3-key backend-lambda.zip
