#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage:"
  echo "  $ $(basename -- "$0") <env>"
  echo "Examples:"
  echo "  $ $(basename -- "$0") dev"
  echo "  $ $(basename -- "$0") prod"
  exit 1
fi

set -euo pipefail # exit on error; treat unset variables as errors; exit on errors in piped commands
SELF_DIR="$(perl -e 'use File::Basename; use Cwd "abs_path"; print dirname(abs_path(@ARGV[0]));' -- "$0")" # figure out the absolute path to the current script, regardless of pwd (perl is more cross-platform than realpath; https://stackoverflow.com/a/30795461)
ROOT_DIR="$SELF_DIR/.."
BUILD_DIR="$SELF_DIR/../build"
ZIP_FILE_LOCAL="$SELF_DIR/../lambda.zip"
ZIP_FILE_REMOTE="backend-lambda.zip" # note: this needs to be in sync with the relevant TF config
REMOVE_PACKAGES="react react-dom react-scripts" # remove packages we KNOW we won't need on the backend (this takes node_modules from 244M to 19M)

# Build the backend code into a self-contained zipfile
(
  cd "$ROOT_DIR"
  npm run backend-build
  ./scripts/app-version-get > "$BUILD_DIR/deployed-app-version"
  cd "$BUILD_DIR"
  mv index-backend.js index.js # TODO: Update TF config to make this unnecessary
  cp ../package* . # use the same dependencies from root
  npm uninstall --save $REMOVE_PACKAGES # ...but remove specific ones we KNOW we don't need for the backend
  rm -rf node_modules && npm install --production # reinstall to get rid of the above packages and their dependency trees (this takes node_modules from 244M to 19M)
  zip -r "$ZIP_FILE_LOCAL" * # create zipfile to root
  du -hs "$ZIP_FILE_LOCAL" # document the size of the zipfile (so someone can notice if it suddenly balloons)
)

# Upload code to S3 & clean up
aws s3 cp \
  "$ZIP_FILE_LOCAL" \
  "s3://symptomradar-$1-backend-code/$ZIP_FILE_REMOTE"
rm -vf "$ZIP_FILE_LOCAL"

# Let Lambda know function code has been updated
aws lambda update-function-code \
  --function-name "symptomradar-$1-backend-api" \
  --s3-bucket "symptomradar-$1-backend-code" \
  --s3-key "$ZIP_FILE_REMOTE"
aws lambda update-function-code \
  --function-name "symptomradar-$1-backend-worker" \
  --s3-bucket "symptomradar-$1-backend-code" \
  --s3-key "$ZIP_FILE_REMOTE"
