#!/bin/bash

if [ "$#" -ne 3 ]; then
  echo "Usage:"
  echo "  $ $(basename -- "$0") <env> <npm-build-script>      <s3-upload-path>"
  echo "Examples:"
  echo "  $ $(basename -- "$0") dev   frontend-embed-v1-build /embed/v1/"
  echo "  $ $(basename -- "$0") prod  frontend-main-build     /"
  exit 1
fi

set -euo pipefail # exit on error; treat unset variables as errors; exit on errors in piped commands
SELF_DIR="$(perl -e 'use File::Basename; use Cwd "abs_path"; print dirname(abs_path(@ARGV[0]));' -- "$0")" # figure out the absolute path to the current script, regardless of pwd (perl is more cross-platform than realpath; https://stackoverflow.com/a/30795461)
BUILD_DIR="$SELF_DIR/../build"
DEFAULT_LANG="fi"

# Build the frontend static files
(
  INLINE_RUNTIME_CHUNK=false GENERATE_SOURCEMAP=false npm run "$2" # don't inline webpack runtime (inline scripts are categorically banned by our CSP)
  (cd "$BUILD_DIR" && rm -fv index-*.html *manifest* service-worker.js) # remove some cruft we don't need
  npm run ts-node "$SELF_DIR/../scripts/translate-frontend.ts"
  (cd "$BUILD_DIR" && [ ! -f index.$DEFAULT_LANG.html ] || mv -v index{.$DEFAULT_LANG,}.html) # if translated index files got generated, replace the templated index HTML with the default-lang one
)

# Upload & clean up files that can be aggressively cached (i.e. for 1 day)
aws s3 cp \
  --cache-control=max-age=86400 \
  --recursive \
  "$BUILD_DIR/static/" "s3://symptomradar-$1-frontend-code${3}static/"
rm -rfv "$BUILD_DIR/static/"

# Upload & clean up files that need to be served fresh
aws s3 cp \
  --cache-control=max-age=15 \
  --recursive \
  "$BUILD_DIR/" "s3://symptomradar-$1-frontend-code${3}"
rm -rfv "$BUILD_DIR/"
